status = [
  # Buildkite: impure builds
  "buildkite/Bcc",
  # Hydra: build for required jobset
  "ci/hydra:Bcc:Bcc:required",
]
timeout_sec = 3600
required_approvals = 1
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
